version: 0.0
os: linux

files:
  - source: /         # Repository(S3)
    destination: /home/ubuntu/app   # EC2 instance

permission:
  - object: /home/ubuntu/app/
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: root