version: 0.0
os: linux

files:
  - source: /         # Repository(S3)
    destination: /home/ubuntu   # EC2 instance

permission:
  - object: /home/ubuntu/
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu