name: build

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: CICD
    env:
      APPLICATION: ${{secrets.APPLICATION}}
      APPLICATION_TEST: ${{secrets.APPLICATION_TEST}}
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'temurin' # jdk 제공
      
      - name: Create resources in test
        run : mkdir ./src/test/resources
        
      - name: Create application.yml(for test)
        run : touch ./src/test/resources/application.yml
        
      - name: Copy Secrets to applicatoin.yml(for test)
        run : echo "$APPLICATION_TEST" > ./src/test/resources/application.yml
        
      - name: Copy Secrets to application.yml(for build)
        run : echo "$APPLICATION" > ./src/main/resources/application.yml
      
      - name: Grant execution permission for gradlew
        run: chmod +x gradlew
        
      - name : Build
        run: ./gradlew clean build
