name: build

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      APPLICATION: ${{secrets.APPLICATION_MAIN}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'temurin' # jdk 제공사
      - name: Create resources directory
        run:  mkdir ./src/main/resources
      
      - name: Create application.yml(for build)
        run : touch ./src/main/resources/application.yml
      - name: Copy Secrets to application.yml(for build)
        run : echo "${{env.APPLICATION}}" > ./src/main/resources/application.yml
      
      - name: Grant execution permission for gradlew
        run: chmod +x gradlew
        
      - name : Build
        run: ./gradlew clean build
